import WebSocket from 'ws';
const token = process.env.RISEZOME_SESSION_TOKEN;
const url = `ws://127.0.0.1:4337/ws/events?token=${token}`;
console.log('connecting to', url);
const ws = new WebSocket(url, { origin: 'http://127.0.0.1:4337' });
const t0 = Date.now();
ws.on('open', () => console.log(`onopen @ ${Date.now()-t0}ms`));
ws.on('message', (data) => console.log(`message @ ${Date.now()-t0}ms:`, data.toString()));
ws.on('close', (code, reason) => { console.log(`close @ ${Date.now()-t0}ms code=${code} reason=${reason}`); process.exit(0); });
ws.on('error', (err) => { console.log(`error @ ${Date.now()-t0}ms:`, err.message); process.exit(1); });
setTimeout(() => { console.log('timeout, closing'); ws.close(); }, 5000);
