-- Dev-only seed. `supabase db reset` runs this AFTER migrations against the
-- LOCAL stack. Production / `supabase db push` never run it.
--
-- Intentionally empty: a fresh local stack comes up with the schema and no
-- rows, and you onboard normally (sign in with Google → create a workspace →
-- connect sources), generating real local data. Add fixtures here later if a
-- reproducible demo dataset becomes useful.
