/**
 * Start-all preflight: self-heal the two prerequisites a fresh checkout misses,
 * so the apps don't crash cryptically.
 *
 *   1. Workspace packages consumed as built `dist/` (@risezome/engine, crypto,
 *      shared-types). On a fresh `pnpm install` — or after editing a package —
 *      `dist/` is missing or stale and the portal/bot-worker die with
 *      ERR_MODULE_NOT_FOUND. We detect that and run `pnpm build`.
 *   2. The active env files (apps/bot-worker/.env, apps/portal/.env.local) are
 *      GENERATED by use-env.sh from the per-developer `.env.dev` secrets. If they
 *      are missing we generate them — unless the `.env.dev` secrets don't exist
 *      yet, which we can't create, so we surface the exact `cp` commands.
 *
 * Pure detection helpers (no I/O beyond `fs.stat`) so they're deterministic to
 * unit-test against a temp dir; `runBuild` is the one side-effecting spawn.
 */

import { spawn } from 'node:child_process';
import { existsSync, statSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/** Workspace packages the apps import as compiled `dist/`, in build order. */
export const BUILT_PACKAGES = ['shared-types', 'crypto', 'engine'] as const;

/** Newest file mtime (ms) under a directory tree, or 0 when the dir is absent. */
function newestMtime(dir: string): number {
  if (!existsSync(dir)) return 0;
  let newest = 0;
  const walk = (d: string): void => {
    for (const ent of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, ent.name);
      if (ent.isDirectory()) walk(p);
      else {
        const m = statSync(p).mtimeMs;
        if (m > newest) newest = m;
      }
    }
  };
  walk(dir);
  return newest;
}

/**
 * True when any built package needs a (re)build — its `dist/` is missing, or its
 * `src/` has been edited more recently than its `dist/` (stale). `tsc -b` is
 * incremental, so running the build on a false positive is cheap.
 */
export function needsBuild(repoRoot: string): boolean {
  return BUILT_PACKAGES.some((pkg) => {
    const dist = join(repoRoot, 'packages', pkg, 'dist');
    const src = join(repoRoot, 'packages', pkg, 'src');
    if (!existsSync(join(dist, 'index.js'))) return true; // never built
    return newestMtime(src) > newestMtime(dist); // stale
  });
}

export interface EnvState {
  /** Both active env files exist (apps can boot). */
  readonly activePresent: boolean;
  /** Both per-developer `.env.dev` secret files exist (we can generate). */
  readonly secretsPresent: boolean;
  /** The `.env.dev` paths that are missing (for the actionable message). */
  readonly missingSecrets: readonly string[];
}

export function envState(repoRoot: string): EnvState {
  const active = [
    join(repoRoot, 'apps', 'bot-worker', '.env'),
    join(repoRoot, 'apps', 'portal', '.env.local'),
  ];
  const secrets = [
    join(repoRoot, 'apps', 'portal', '.env.dev'),
    join(repoRoot, 'apps', 'bot-worker', '.env.dev'),
  ];
  const missingSecrets = secrets.filter((p) => !existsSync(p));
  return {
    activePresent: active.every((p) => existsSync(p)),
    secretsPresent: missingSecrets.length === 0,
    missingSecrets,
  };
}

/** Run the workspace build, streaming each output line to `emit`. Resolves with
 *  the child exit code (-1 on spawn error). */
export function runBuild(
  repoRoot: string,
  emit: (line: string) => void,
  cmd: { command: string; args?: string[] } = { command: 'pnpm', args: ['build'] },
): Promise<number | null> {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn(cmd.command, cmd.args ?? ['build'], { cwd: repoRoot });
    } catch (err) {
      emit(`[console] build spawn error: ${(err as Error).message}`);
      resolve(-1);
      return;
    }
    const onData = (buf: Buffer): void => {
      for (const line of buf.toString().split('\n')) if (line.trim().length > 0) emit(line);
    };
    child.stdout?.on('data', onData);
    child.stderr?.on('data', onData);
    child.on('error', (err) => emit(`[console] build error: ${err.message}`));
    child.on('close', (code) => resolve(code));
  });
}
